### ISSUE TITLE
api返回错误码500

### ISSUE THREAD

**Issue by YujioNako** [fumiama/nsfw-detecter-azfun#1]
最近使用接口时发现api返回错误码，无法正常使用了。请问是api停用了嘛？

**Comment by fumiama** [comment]
代码没动过，确实不行了，目前先简单修了一下/nsfw，/tag还不能用。

**Comment by fumiama** [comment]
修了一遍，现在全好了，顺便`/tag`我也改成了像`/nsfw`那样的支持多图，返回时的json多了个`[]`。

**Comment by YujioNako** [comment]
> 修了一遍，现在全好了，顺便`/tag`我也改成了像`/nsfw`那样的支持多图，返回时的json多了个`[]`。

好的谢谢您
